// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY-B700zipo2-wDxyGAHNIrSVrRy_rEdc',
    appId: '1:1070294164448:web:40f2ec29b4056434e28185',
    messagingSenderId: '1070294164448',
    projectId: 'realpj-flutter-project',
    authDomain: 'realpj-flutter-project.firebaseapp.com',
    storageBucket: 'realpj-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACztWNE4xNTqfxx7SoMxrC7S46lec1Oeo',
    appId: '1:1070294164448:android:fe5539be95421bf1e28185',
    messagingSenderId: '1070294164448',
    projectId: 'realpj-flutter-project',
    storageBucket: 'realpj-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqKZcDFu6AtGqpARJrcVcUTbRFnjSyeVA',
    appId: '1:1070294164448:ios:9e6cee5ada77536ce28185',
    messagingSenderId: '1070294164448',
    projectId: 'realpj-flutter-project',
    storageBucket: 'realpj-flutter-project.appspot.com',
    iosClientId: '1070294164448-tnbufvnhvgecgae8u1g9b24mv22mqqrm.apps.googleusercontent.com',
    iosBundleId: 'zw.darlhp.realpj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqKZcDFu6AtGqpARJrcVcUTbRFnjSyeVA',
    appId: '1:1070294164448:ios:9e6cee5ada77536ce28185',
    messagingSenderId: '1070294164448',
    projectId: 'realpj-flutter-project',
    storageBucket: 'realpj-flutter-project.appspot.com',
    iosClientId: '1070294164448-tnbufvnhvgecgae8u1g9b24mv22mqqrm.apps.googleusercontent.com',
    iosBundleId: 'zw.darlhp.realpj',
  );
}
